include( "shared.lua" )

function GM:Initialize()
	sound.Play( "ambient/explosions/exp1.wav", Vector( 0, 0, 0 ) )
end

net.Receive( "popupHelp", function()
	local ply = net.ReadEntity()
	local helpFrame = vgui.Create( "DFrame" )
	helpFrame:SetPos( 0, 0 )
	helpFrame:SetSize( ScrW(), ScrH() )
	helpFrame:SetTitle( "Help" )
	helpFrame:SetVisible( true )
	helpFrame:SetDraggable( false )
	helpFrame:ShowCloseButton( true )
	helpFrame:MakePopup()
	local html = vgui.Create( "HTML", helpFrame )
	html:Dock( FILL )
	html:OpenURL( "https://github.com/Leeous/battlegrounds" )
end )

net.Receive( "popupTeamSelect", function()
	local ply = net.ReadEntity()
	local teamSelector = vgui.Create( "DFrame" )
	teamSelector:SetSize( ScrW() * 0.50, ScrH() * 0.75 )
	teamSelector:SetTitle( "Select your team" )
	teamSelector:SetVisible( true )
	teamSelector:SetDraggable( false )
	teamSelector:ShowCloseButton( true )
	teamSelector:MakePopup()
	teamSelector:Center()

	local playerList = vgui.Create( "DListView", teamSelector )
	playerList:SetPos(300, 50)
	playerList:SetSize(ScrW() * 0.30, ScrH() * 0.50)
	playerList:SetMultiSelect( false )
	playerList:AddColumn( "Name" )
	playerList:AddColumn( "Team" )
	playerList:AddLine( "Leeous", "1" )

	-- Change teams
	local changeTeamPlayers = vgui.Create( "DButton", teamSelector )
	changeTeamPlayers:SetText( "Players" )		
	changeTeamPlayers:SetPos( 25, 50 )
	changeTeamPlayers:SetSize( 250, 20 )
	changeTeamPlayers.DoClick = function()
			changeTeam(1)
			teamSelector:Close()
	end
	local changeTeamSpectators = vgui.Create( "DButton", teamSelector )
	changeTeamSpectators:SetText( "Spectators" )		
	changeTeamSpectators:SetPos( 25, 75 )
	changeTeamSpectators:SetSize( 250, 20 )
	changeTeamSpectators.DoClick = function()
			changeTeam(2)
			teamSelector:Close()
	end

	local customButton = vgui.Create( "DButton", teamSelector )
	customButton:SetText( "Example Button" )		
	customButton:SetPos( 25, 100 )
	customButton:SetSize( 250, 20 )

	local customButton1 = vgui.Create( "DButton", teamSelector )
	customButton1:SetText( "Example Button" )		
	customButton1:SetPos( 25, 125 )
	customButton1:SetSize( 250, 20 )
end )

function changeTeam(teamNum)
	sound.Play( "garrysmod/balloon_pop_cute.wav", LocalPlayer():GetPos(), 75, 100, 1 )
	net.Start( "changeTeam" )
	net.WriteEntity(LocalPlayer())
	net.WriteUInt(teamNum, 1)
	net.SendToServer()
end